RCP/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RCP.DB;
using RCP.Models;
using RCP.ViewModel;

namespace RCP.Controllers
{
    public class ClientController : Controller
    {
        private readonly CommonDbContext _context;

        public ClientController(CommonDbContext context)
        {
            _context = context;
        }

        [Authorize]
        [HttpPost]
        public async  Task<IActionResult> Create(CreateClientViewModel clientvm)
        {
            if (!ModelState.IsValid)
                return View(clientvm);

            _context.Clients.Add(new Client
            {
                Name = clientvm.ClientViewModel.Client.Name,
                Representant = clientvm.ClientViewModel.Client.Representant,
                ERP_ID = clientvm.ClientViewModel.Client.ERP_ID,
                Description = clientvm.ClientViewModel.Client.Description
            });

            await _context.SaveChangesAsync();

            return RedirectToAction("Index","Report");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var clientViewModel = new ClientViewModel();
            return View();
        }
    }
}

RCP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RCP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                @if (User.Identity.IsAuthenticated)
                {
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Raporty</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Create">Stwórz raport</a>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Create">Stwórz klienta</a>
                    </li>
                    @* <li> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Statistic" asp-action="Index">Statystyki</a> *@
                    @* </li> *@
                    <li class="nav-item" style="align-content:end">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Wyloguj</a>
                    </li>
                </ul>
                }
                else
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Zaloguj</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - RCP
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>